spa_spa_homepage:
    path:     /
    defaults: { _controller: SpaSpaBundle:Default:index }
    
spa_spa_admin:
    path: /admin/configuration
    defaults: { _controller: SpaSpaBundle:Admin:index }

spa_spa_admin_articles:
    path: /admin/configuration/articles
    defaults: { _controller: SpaSpaBundle:Admin:configurateArticles }
spa_spa_admin_add_articles:
    path: /admin/configuration/articles
    defaults: { _controller: SpaSpaBundle:Admin:addArticles }