spa_spa_homepage:
    path:     /
    defaults: { _controller: SpaSpaBundle:Default:index }
    
spa_spa_admin:
    path: /admin/configuration
    defaults: { _controller: SpaSpaBundle:Admin:index }





spa_spa_admin_articles:
    path: /admin/configuration/articles
    defaults: { _controller: SpaSpaBundle:Admin:configurateArticles }
    
spa_spa_admin_allarticles:
    path: /admin/articles
    defaults: {_controller: SpaSpaBundle:Admin:allArticles }
    
spa_spa_admin_modifarticles:
    path: /admin/modification/articles/{id}
    defaults: {_controller: SpaSpaBundle:Admin:modifArticles }
    
spa_spa_admin_savemodifarticles:
    path: /admin/save/articles
    defaults: {_controller: SpaSpaBundle:Admin:savemodifArticles}
    
spa_spa_admin_deletearticles:
    path: /admin/delete/articles/{id}
    defaults: {_controller: SpaSpaBundle:Admin:deleteArticles}
    
    
    
    
    
    
spa_spa_admin_races:
    path: /admin/configuration/races
    defaults: {_controller: SpaSpaBundle:Admin:configurateRaces }
       
spa_spa_admin_allraces:
    path: /admin/races
    defaults: {_controller: SpaSpaBundle:Admin:allRaces }
    
spa_spa_admin_modifraces:
    path: /admin/modification/races/{id}
    defaults: {_controller: SpaSpaBundle:Admin:modifRaces }
    
spa_spa_admin_savemodifraces:
    path: /admin/save/races
    defaults: {_controller: SpaSpaBundle:Admin:savemodifRaces}

spa_spa_admin_deleteraces:
    path: /admin/delete/races/{id}
    defaults: {_controller: SpaSpaBundle:Admin:deleteRaces}




spa_spa_admin_alltags:
    path: /admin/tags
    defaults: {_controller: SpaSpaBundle:Admin:allTags }
    
spa_spa_admin_modiftags:
    path: /admin/modification/tags/{id}
    defaults: {_controller: SpaSpaBundle:Admin:modifTags}
    
spa_spa_admin_savemodiftags:
    path: /admin/save/tags
    defaults: {_controller: SpaSpaBundle:Admin:savemodifTags}    
    
spa_spa_admin_tags:
    path: /admin/configuration/tags
    defaults: {_controller: SpaSpaBundle:Admin:configurateTags }
    
spa_spa_admin_deletetags:
    path: /admin/delete/tags/{id}
    defaults: {_controller: SpaSpaBundle:Admin:deleteTags}
    
    
    
spa_spa_admin_pets:
    path: /admin/configuration/pets
    defaults: {_controller: SpaSpaBundle:Admin:configuratePets }
    
spa_spa_admin_allpets:
    path: /admin/pets
    defaults: {_controller: SpaSpaBundle:Admin:allPets}
    
spa_spa_admin_modifpets:
    path: /admin/modification/pets/{id}
    defaults: {_controller: SpaSpaBundle:Admin:modifPets}
    
spa_spa_admin_savemodifpets:
    path: /admin/save/pets
    defaults: {_controller: SpaSpaBundle:Admin:savemodifPets}
    
spa_spa_admin_deletepets:
    path: /admin/delete/pets/{id}
    defaults: {_controller: SpaSpaBundle:Admin:deletePets}    
    
    
    
    
spa_spa_admin_staff:
    path: /admin/configuration/staff
    defaults: {_controller: SpaSpaBundle:Admin:configurateStaff }
    
spa_spa_admin_modifstaff:
    path: /admin/modification/staff/{id}
    defaults: {_controller: SpaSpaBundle:Admin:modifStaff}
    
spa_spa_admin_allstaff:
    path: /admin/staff
    defaults: {_controller: SpaSpaBundle:Admin:allStaff}

spa_spa_admin_savemodifstaff:
    path: /admin/save/staff
    defaults: {_controller: SpaSpaBundle:Admin:savemodifStaff}
    
spa_spa_admin_deletestaff:
    path: /admin/delete/staff/{id}
    defaults: {_controller: SpaSpaBundle:Admin:deleteStaff}